def coffeerobot():
    print("take milk")
    print("add coffee")
    print("boil water")
    print("mix")
    print("pour into cup")
    print("add sugar")
    print("coffee is ready")
    print("----------------")

coffeerobot()
coffeerobot()
coffeerobot()
coffeerobot()
coffeerobot()